// src/comp/DevelopedBy.svelte
<div class="root">
  <img
    width="24"
    height="24"
    class="icon-wrap"
    src="/assets/icon-yahht.svg"
    alt="Yahht Logo"
  />
  <div>Developed by Yahht</div>
</div>

<style>
  .root {
    display: flex;
    align-items: center;
    font-size: 14px;
  }

  .icon-wrap {
    width: 24px;
    height: 24px;
    margin-right: 8px;
  }
</style>

// src/components/DevelopedBy.tsx
import styled from 'styled-components'

const Root = styled.div`
  display: flex;
  align-items: center;
  font-size: 14px;
`

const IconWrap = styled.img`
  width: 24px;
  height: 24px;
  margin-right: 8px;
`

export const DevelopedBy = () => {
  return (
    <Root>
      <IconWrap width="24" height="24" src="/assets/icon-yahht.svg" alt="Yahht Logo" />
      <div>Developed by Yahht</div>
    </Root>
  )
}
