// src/App.tsx
import { useEffect, useState } from 'react'
import { Router } from '@reach/router'
import cookie from 'js-cookie'
import UserStore from './store/UserStore'
import { sendMessageToExt } from './utils/config'
import { ACTION_LOGIN } from './utils/actions'
import { PageIndex } from './pages/PageIndex'
import { PageLogin } from './pages/PageLogin'
import { PageOnBoarding } from './pages/PageOnBoarding'

export function App() {
  const [dataLoaded, setDataLoaded] = useState(false)

  useEffect(() => {
    ;(async () => {
      const AUTHORIZATION = cookie.get('token')

      if (AUTHORIZATION) {
        await UserStore.setAndFetchUser(AUTHORIZATION)
        sendMessageToExt(ACTION_LOGIN)
      }

      setDataLoaded(true)
    })()
  }, [])

  return dataLoaded ? (
    <Router>
      <PageIndex path="/" />
      <PageOnBoarding path="/onboarding" />
      <PageLogin path="/login" />
    </Router>
  ) : null
}

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Router, Route } from "svelte-navigator";
  import cookie from "js-cookie";
  import axios from "axios";
  import { storeToken, storeUser } from "./store.js";
  import { apiUrl, sendMessageToExt } from "./config.js";
  import PageIndex from "./pages/PageIndex.svelte";
  import PageLogin from "./pages/PageLogin.svelte";
  import PageOnBoarding from "./pages/PageOnBoarding.svelte";

  const AUTHORIZATION = cookie.get("token");

  if (AUTHORIZATION) {
    storeToken.set(AUTHORIZATION);
  }

  let dataLoaded;

  onMount(async () => {
    if (AUTHORIZATION) {
      const { data } = await axios.get(`${apiUrl}/profile`, {
        headers: { AUTHORIZATION },
      });

      storeUser.set(data);

      sendMessageToExt("userLoginIn");
    }

    dataLoaded = true;
  });
</script>

{#if dataLoaded}
  <Router>
    <Route path="/" component={PageIndex} />
    <Route path="/onboarding" component={PageOnBoarding} />
    <Route path="/login" component={PageLogin} />
  </Router>
{/if}
